version: '3.4'

services:
  crawlxemayv2:
    image: crawlxemayv2
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 CrawlXeMay\spiders\xemayhoangkien.py "]
    ports:
      - 5678:5678
